version: '3'

services:

  postgres:
    build: images/postgres
    image: modernproject/postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  migration:
    restart: on-failure
    build: 
      context: ../backend/
      dockerfile: /compose/local/Dockerfile
    image: modernproject/backend
    working_dir: /backend
    command: python3 manage.py migrate
    volumes:
      - ../backend:/backend
    depends_on:
      - postgres
    environment:
      - DJANGO_READ_DOT_ENV_FILE=True

  collectstatic:
    restart: on-failure
    build:
      context: ../backend/
      dockerfile: /compose/local/Dockerfile
    image: modernproject/backend
    working_dir: /backend
    command: python3 manage.py collectstatic --no-input
    volumes:
      - ../backend:/backend
    environment:
      - DJANGO_READ_DOT_ENV_FILE=True

  backend:
    restart: always
    build: 
      context: ../backend/
      dockerfile: /compose/local/Dockerfile
    image: modernproject/backend
    working_dir: /backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - collectstatic
      - redis
    restart: always
    environment:
      - DJANGO_READ_DOT_ENV_FILE=True

  frontend:
    restart: always
    build:
      context: ../fontend/
      dockerfile: /compose/local/Dockerfile
    build: ../frontend/compose/local
    image: modernproject/frontend
    user: node
    command: yarn start --host 0.0.0.0
    working_dir: /frontend
    volumes:
      - ../frontend:/frontend
    ports:
      - "8080:8080"

  nginx:
    restart: always
    build: images/nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./images/nginx/conf.d/modernproject.conf:/etc/nginx/conf.d/default.conf
      - ../backend/static:/www/static

  redis:
    restart: always
    image: redis
    expose:
      - "6379"